henry_homepage/blog/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static
from haystack.generic_views import SearchView
from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    url(r'^create/$', views.PostCreateView.as_view(), name='create'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.PostUpdateView.as_view(), name='update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.PostDeleteView.as_view(), name='delete'),
    url(r'^tag/(?P<tag>\w+)/$', views.IndexView.as_view(), name='tagpage'),
    url(r'^search/$', views.IndexView.as_view(), name='search'),
]

henry_homepage/henry_homepage/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import include
from django.conf.urls.static import static

urlpatterns = [
    url('^', include( ('home.urls', 'home'), namespace='home') ),
    url('^blog/', include( ('blog.urls', 'blog'), namespace='blog') ),
    url('admin/', admin.site.urls),
    #url(r'^tinymce/', include('tinymce.urls') ),
    #url(r'^markdownx/', include('markdownx.urls') ),
    url(r'^martor/', include('martor.urls') ),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

henry_homepage/home/urls.py
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.generic.base import TemplateView
from . import views

urlpatterns = [
    url(r'^$', views.HomeView.as_view(), name='index'),
    #url(r'^about$', TemplateView.as_view( template_name = 'home/about.html'), name='about'),
    url(r'^about$', views.AboutView.as_view(), name='about'),
    url(r'^contact$', TemplateView.as_view( template_name = 'home/contact.html'), name='contact'),
]

henry_homepage/blog/models.py
from django.db import models
from django.utils import timezone
from taggit.managers import TaggableManager
from django.urls import reverse
#from tinymce.models import HTMLField
#from markdownx.models import MarkdownxField
#from markdownx.utils import markdownify
from martor.models import MartorField

# Create your models here.
class Post(models.Model):
    title = models.CharField( max_length=200)
    author = models.CharField(max_length=50, default='Henry Yang')
    created_date = models.DateTimeField( default= timezone.now )
    published_date = models.DateTimeField( default= timezone.now )
    #content = HTMLField( )
    #content = MarkdownxField()
    content = MartorField()
    post_logo = models.FileField(max_length=100, default='', blank=True)
    tags = TaggableManager()

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def save(self, *args, **kwargs):
        self.published_date = timezone.now()
        super().save(*args, **kwargs)  # Call the "real" save() method.

    #@property
    #def formatted_markdown(self):  # <--- We'll need this for views.py later
    #    return markdownify(self.content)

    def __unicode__(self):
        return self.title

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail', kwargs  = {'pk':self.pk} )

henry_homepage/home/models.py
from django.db import models

# Create your models here.

henry_homepage/blog/forms.py
from django import forms
from .models import Post

class PostForm(forms.ModelForm):
    title = forms.CharField(
        widget=forms.TextInput(
            attrs={'class': 'form-control input-area', 'placeholder': 'Enter your name'}
        ),
        required=True
    )
    class Meta:
        widgets = {'title': forms.TextInput(attrs={'size':100})}

class PostAdminForm(forms.ModelForm):
    class Meta:
        widgets = {'title': forms.TextInput(attrs={'size':10})}

henry_homepage/blog/views.py
from django.views import generic
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import  reverse_lazy
from django.shortcuts import render, render_to_response
from django.core.paginator import Paginator
from django.db.models import Q
from taggit.models import  Tag
from django import forms
from django.forms.models import modelform_factory
from haystack.query import SearchQuerySet
from haystack.inputs import AutoQuery, Exact, Clean
from haystack.generic_views import SearchView
from . models import Post

class IndexView(ListView):
    model = Post
    template_name = 'blog/index.html'
    context_object_name = 'posts'
    paginate_by = 5

    def get_queryset(self):
        self.template_name = 'blog/index.html'
        # Filter by tag
        if( 'tag' in self.kwargs.keys() ):
            post_list = Post.objects.filter(tags__name=self.kwargs['tag']).order_by('-published_date')
            '''
            self.template_name = 'search/search_page.html'
            query = self.request.GET.get('q')
            post_list = SearchQuerySet().autocomplete(tags=query).order_by('-published_date')
            '''
        elif( self.request.GET.get('q') ):
            self.template_name = 'search/search_page.html'
            query = self.request.GET.get('q')
            #post_list = SearchQuerySet().autocomplete(content_auto=query)
            post_list = SearchQuerySet().autocomplete(content__contains=query).order_by('-published_date')
        else:
            post_list = Post.objects.all().order_by('-published_date')
        return post_list

    def get_context_data(self, **kwargs):
        # Variable
        page_header_message = ''
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['tags'] = Tag.objects.all()
        #
        if( 'tag' in self.kwargs.keys() ):
            page_header_message = "Posts tagged by " + self.kwargs['tag']
            context['tag'] = self.kwargs['tag']
        elif( self.request.GET.get('q') ):
            page_header_message = "Posts contains " + self.request.GET.get('q')
            context['query'] = self.request.GET.get('q')
        else:
            page_header_message = "Welcome to Henry's Blog"
        context['page_header_message'] = page_header_message
        return context

class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super().get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['tags'] = Tag.objects.all()
        return context

class PostCreateView(CreateView):
    model = Post
    template_name_suffix = '_template'

    form_class = modelform_factory(Post,
            exclude=['post_logo', 'created_date', 'published_date'],
            widgets = {'title': forms.TextInput(attrs={'size':100}),
                       'author': forms.TextInput(attrs={'size':100}),
                      }
            )

class PostUpdateView(UpdateView):
    model = Post
    template_name_suffix = '_template'

    form_class = modelform_factory(Post,
            exclude=['post_logo', 'created_date', 'published_date'],
            widgets = {'title': forms.TextInput(attrs={'size':100}),
                       'author': forms.TextInput(attrs={'size':100}),
                      }
            )

class PostDeleteView(DeleteView):
    model = Post
    # FIXME: no use of the template_name
    template_name = 'blog/confirm_delete.html'
    success_url = reverse_lazy( 'blog:index' )

henry_homepage/home/views.py
from django.views import generic
from django.shortcuts import render

class HomeView(generic.base.TemplateView):
    template_name = 'home/index.html'

class AboutView(generic.base.TemplateView):
    template_name = 'home/about.html'

henry_homepage/blog/templates/blog/category_card.html
{% comment "" %}
NOTE: Input is tags include all tag from taggit.objects.all()
{% endcomment %}

<!-- Categories -->
<div class="card my-4">
     <h5 class="card-header">Categories</h5>
     <div class="card-body">
         {% for tag in tags %}
         {% if forloop.counter0|divisibleby:2 %}
         <div class="row">
         {% endif %}
             <div class="col-lg-6">
                 <ul class="list-unstyled mb-0">
                     <li>
                         <a href="{% url 'blog:tagpage' tag %}">{{ tag }}</a>
                     </li>
                 </ul>
             </div>
         {% if forloop.counter|divisibleby:2 or forloop.last %}
         </div>
         {% endif %}
         {% endfor %}
     </div>
    <br>
</div>
<!-- End Of Categories -->

henry_homepage/blog/templates/blog/confirm_delete.html
{% extends 'base/base.html' %}
{% block title %}
Henry's Blog
{% endblock %}

{% block page_header_content %}
<h1 class="text-center" style="color: white"> Welcome to Henry's Blog</h1>
{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <!-- MAIN BODY -->
        <div class="col-sm-8">
            <div class="card my-4">
                <h1 class="card-header">Delete Post</h1>
                <h2 class="card-body">
                    Are you sure want to delte the post?<br>
                    <span style="color:blue">{{ post.title }}</span>
                </h2>
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                        <a class="btn btn-outline-secondary" href="{% url 'blog:detail' post.id %}">Cancel</a>
                    </div>
                </form>

            </div>
        </div>
        <!-- SIDEBAR -->
        {% include 'blog/sidebar.html' %}
    </div>

</div>

{% endblock %}

henry_homepage/blog/templates/blog/detail.html
{% extends 'base/base.html' %}
{% load martortags %}
{% block title %}
{{ post.title }}
{% endblock %}

{% block body %}
    <div class='container'>
        <div class="row">

            <!-- POST -->
            <div class="col-sm-8">
                <div style="
                            background-clip:border-box;
                            border: 1px solid rgba(0,0,0,0.125);
                            border-radius: 0.25rem;
                            position:relative;
                            margin-top: 20px;
                            display: -ms-flexbox;
                            -ms-flex-direction: column;
                            flex-direction: column;
                            ">
                    <!-- Title -->
                    <h1 class="card-title">{{ post.title }}</h1>

                    <!-- Author -->
                    <p class="card-subtitle">by {{ post.author }}
                        <!-- Edit -->
                        <a class="" href="{% url 'blog:update' post.id %}">
                            <span class="glyphicon glyphicon-edit"></span>
                        </a>
                        <!-- Delete -->
                        <a class="" href="{% url 'blog:delete' post.id %}">
                            <span class="secondary glyphicon glyphicon-trash"></span>
                        </a>
                    </p>

                    <!-- Date/Time -->
                    <p class="card-subtitle">Posted on - {{ post.published_date|date:'D d F Y H:i' }}</p>
                    <hr>

                    <!-- Preview Image -->
                    {% if post.post_logo != '' %}
                    <img class="img-fluid rounded" src="{{ post.post_logo.url }}" alt="">
                    <hr>
                    {% endif %}

                    <!-- Post Content -->
                    {% comment "used for tinymce"%}
                    <p clas="card-body">{{ post.content|safe }}</p>

                    <p clas="card-body">{{ post.formatted_markdown|safe }}</p>
                    {% endcomment %}
                    <p clas="card-body">{{ post.content|safe_markdown }}</p>
                    <hr>

                    <!-- TAGS -->
                    <p class="card-footer"><b>TAG:&nbsp</b>
                        {% for tag in post.tags.all %}
                        <a href="{% url 'blog:tagpage' tag %}">{{ tag }}
                            {% if not forloop.last %},{% endif %}
                        </a>
                        {% endfor %}
                    </p>
                </div>
            </div>
            <!-- END OF POST -->

            {% include 'blog/sidebar.html' %}
        </div>

    </div>
{% endblock %}

henry_homepage/blog/templates/blog/operation_card.html
{% comment "" %}
NOTE: Input is tags include all tag from taggit.objects.all()
{% endcomment %}

<!-- ADD -->
<div class="card my-4">
    <h5 class="card-header">Operation</h5>
    <div class="card-body">
        <div class="row">
            <div class="col-sm-6">
                <a class="btn btn-info " href="{% url 'blog:create' %}">
                    <span class="glyphicon glyphicon-plus">AddPost</span>
                </a>
            </div>
            <div class="col-sm-6">
            </div>
        </div>
    </div>
</div>
<!-- End Of ADD -->

henry_homepage/blog/templates/blog/post_thumbnail.html
{% load martortags %}
<div class="card mb-4">
    {% if post.post_logo != '' %}
    <a href="{% url 'blog:detail' post.id %}">
        <img class="img-fluid rounded" src="{{ post.post_logo.url }}" alt="" >
    </a>
    {% endif %}
    <div class="card-body">
        <!-- <h2 class="card-title">{{ post.title }}</h2> -->
        <a class="card-title" href="{% url 'blog:detail' post.id %}">
            <h2 style="color:darkblue">{{ post.title }}</h2>
        </a>
        {% comment "used for tinymce"%}
        <p clas="card-body">{{ post.content|safe }}</p>
        <p class="card-text">{{ post.content|safe|truncatewords_html:20 }}</p>
        <p clas="card-body">{{ post.formatted_markdown|safe|truncatewords_html:20 }}</p>
        {% endcomment %}
        <p clas="card-body">{{ post.content|safe_markdown|truncatewords_html:20 }}</p>
        {% for tag in post.tags.all %}
        <a href="{% url 'blog:tagpage' tag %}">{{ tag }}
            {% if not forloop.last %},{% endif %}
        </a>
        {% endfor %}
        <br>
        <!-- View Detail -->
        <a href="{% url 'blog:detail' post.id %}" class="btn btn-primary">Detail</a>
        <!-- Edit -->
        <a class="" href="{% url 'blog:update' post.id %}">
            <span class="glyphicon glyphicon-edit"></span>
        </a>
        <!-- Delete -->
        <a class="" href="{% url 'blog:delete' post.id %}">
            <span class="glyphicon glyphicon-trash" style="color:gray"></span>
        </a>
    </div>
    <div class="card-footer text-muted">
        Posted on {{ post.published_date|date:'D d M Y H:i' }}
    </div>
</div>

henry_homepage/blog/templates/blog/post_thumbnail_list.html
<!-- Blog Post -->
{% for post in posts %}
{% include 'blog/post_thumbnail.html' %}
{% endfor %}
<!-- Pagination -->
{% include 'blog/paginator.html' %}
<br>

henry_homepage/blog/templates/blog/search_card.html
<!-- Search Widget -->
<div class="card my-4">
    <h5 class="card-header">Search</h5>
    <div class="card-body">
        <form class="input-group" method="GET" action="{% url 'blog:search' %}">
            <input name='q' value="{{ request.GET.q }}" type="text" class="form-control" placeholder="Search for...">
            <span class="input-group-btn">
                <button class="btn btn-success" type="submit">Go!</button>
            </span>
        </form>
    </div>
</div>

henry_homepage/blog/templates/search/thumbnail.html
{% load martortags %}
<div class="card mb-4">
    {% if post.object.post_logo != '' %}
    <a href="{% url 'blog:detail' post.object.id %}">
        <img class="img-fluid rounded" src="{{ post.object.post_logo.url }}" alt="" >
    </a>
    {% endif %}
    <div class="card-body">
        <!-- <h2 class="card-title">{{ post.object.title }}</h2> -->
        <a class="card-title" href="{% url 'blog:detail' post.object.id %}">
            <h2 style="color:darkblue">{{ post.title }}</h2>
        </a>
        {% comment "used for tinymce"%}
        <p clas="card-body">{{ post.content|safe }}</p>
        <p class="card-text">{{ post.content|safe|truncatewords_html:20 }}</p>
        <p clas="card-body">{{ post.formatted_markdown|safe|truncatewords_html:20 }}</p>
        {% endcomment %}
        <p clas="card-body">{{ post.object.content|safe_markdown|truncatewords_html:20 }}</p>
        {% for tag in post.object.tags.all %}
        <a href="{% url 'blog:tagpage' tag %}">{{ tag }}
            {% if not forloop.last %},{% endif %}
        </a>
        {% endfor %}
        <br>
        <!-- View Detail -->
        <a href="{% url 'blog:detail' post.object.id %}" class="btn btn-primary">Detail</a>
        <!-- Edit -->
        <a class="" href="{% url 'blog:update' post.object.id %}">
            <span class="glyphicon glyphicon-edit"></span>
        </a>
        <!-- Delete -->
        <a class="" href="{% url 'blog:delete' post.object.id %}">
            <span class="glyphicon glyphicon-trash" style="color:gray"></span>
        </a>
    </div>
    <div class="card-footer text-muted">
        Posted on {{ post.object.published_date|date:'D d M Y H:i' }}
    </div>
</div>

henry_homepage/home/templates/home/about.html
{% extends 'base/base.html' %}
{% load staticfiles %}

<!-- TITLE -->
{% block title %}
About Henry
{% endblock %}

<!-- Page-HEADER -->
{% block head_content %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet">
    <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'home/resume.min.css' %}" rel="stylesheet">
    <!-- Custom scripts for this template -->
    <script src="{% static 'home/js/resume.min.js' %}"></script>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Plugin JavaScript -->
    <script src="{% static 'vendor/jquery-easing/jquery.easing.min.js' %}"></script>
{% endblock %}

<!-- NAV -->
{% block nav %}
    <nav class="navbar-expand-lg navbar-dark bg-primary fixed-top" id="sideNav">
        <a class="navbar-brand js-scroll-trigger" href="{% url 'home:index' %}">
            <span class="d-none d-lg-block">
                <img class="img-fluid img-profile rounded-circle mx-auto mb-2" src="{% static 'home/images/henry_head_portrait.jpg' %}" alt="">
            </span>
            <span class="d-block d-lg-none">Henry Yang</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#about">About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#experience">Experience</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#education">Education</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#skills">Skills</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#interests">Interests</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link js-scroll-trigger" href="#awards">Awards</a>
                </li>
            </ul>
        </div>
    </nav>

    <div class="container-fluid p-0">
        <!-- ABOUT -->
        <section class="resume-section p-3 p-lg-5 d-flex d-column" id="about">
            <div class="my-auto">
                <h1 class="mb-0">Henry
                    <span class="text-primary">Yang</span>
                </h1>
                <div class="subheading mb-5">
                  <a href="mailto:yanghengmonkey@gmail.com">yanghengmonkey@gmail.com</a>
                </div>
                <p class="lead mb-5">I am a ASIC verfication engineer.</p>
                <div class="social-icons">
                  <a href="https://www.linkedin.com/in/heng-yang-95b83084/">
                    <i class="fab fa-linkedin-in"></i>
                  </a>
                  <a href="https://github.com/yanghengmonkey">
                    <i class="fab fa-github"></i>
                  </a>
                  <a href="https://twitter.com/hashtag/hengyang">
                    <i class="fab fa-twitter"></i>
                  </a>
                  <a href="https://www.facebook.com/profile.php?id=100011561176058">
                    <i class="fab fa-facebook-f"></i>
                  </a>
                </div>
            </div>
        </section>

        <hr class="m-0">
        <!-- EXPERIENCE S-->
        <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="experience">
            <a>My experience</a>
        </section>

        <hr class="m-0">
        <!-- EDUCATION -->
        <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="education">
            <a>My education</a>
        </section>

        <hr class="m-0">
        <!-- SKILLS -->
        <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="skills">
            <a>My skills</a>
        </section>

        <hr class="m-0">
        <!-- INTEREST -->
        <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="interests">
            <a>My interests</a>
        </section>

        <hr class="m-0">
        <!-- AWARDS -->
        <section class="resume-section p-3 p-lg-5 d-flex flex-column" id="awards">
            <a>My awards</a>
        </section>
    </div>
{% endblock %}


{% block page_header %}
{% endblock %}

henry_homepage/home/templates/home/search.html
<div class="masthead">
    <div class="masthead-bg"></div>
    <div class="container h-100">
        <div class="row h-100">
            <div class="col-3 my-auto"></div>
            <div class="col-6 my-auto">
                <div class="masthead-content text-white py-5 py-md-0">
                    <br><br><br><br><br>
                    <form class="input-group" method="GET" action="{% url 'blog:search' %}">
                        <input name='q' value="{{ request.GET.q }}" type="text" class="form-control" placeholder="Search for...">
                        &nbsp;
                        <span class="input-group-btn">
                            <button class="btn btn-success" type="submit">&nbsp&nbsp&nbsp Go! &nbsp&nbsp&nbsp</button>
                        </span>
                    </form>
                </div>
            </div>
            <div class="col-3 my-auto"></div>
        </div>
    </div>
</div>

henry_homepage/templates/base/base.html
<!DOCTYPE html>
{% load martortags %}
<html lang='en'>
    <!-- HEAD -->
    {% block head %}
    <head class="page-header">
       {% block head_content %}

        <title>{% block title %}Henry{% endblock %}</title>

        <meta charset='UTF-8'>
        {% load staticfiles %}

        {% block head_base_link %}
        <link rel='stylesheet' type='text/css' href="{% static 'vendor/bootstrap/css/bootstrap.css' %}" >
        <link rel='stylesheet' type='text/css' href="{% static 'home/home_style.css' %}" >
        <link href="{% static 'admin/css/forms.css' %}" rel="stylesheet" type="text/css" />
        <link href="{% static 'vendor/plugins/css/ace.min.css' %}" type="text/css" media="all" rel="stylesheet" />
        <link href="{% static 'vendor/plugins/css/semantic.min.css' %}" type="text/css" media="all" rel="stylesheet" />
        <link href="{% static 'vendor/plugins/css/resizable.min.css' %}" type="text/css" media="all" rel="stylesheet" />
        <link href="{% static 'vendor/martor/css/martor.min.css' %}" type="text/css" media="all" rel="stylesheet" />
        {% endblock %}

        {% block head_extra_link %}
        {% endblock %}

        {% block head_base_script %}
        <script type="text/javascript" src="/admin/jsi18n/"></script>
        <!-- Boostrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
        {% comment "" %}
        <!--Tinymce Text-Editor (Must be in Head Tag) -->
        <script src="{% static 'vendor/tinymce/js/tinymce/tinymce.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/tinymce/js/tinymce/custom.js' %}" ></script>
        {% endcomment %}
        <script type="text/javascript" src="{% static 'vendor/plugins/js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/plugins/js/ace.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/plugins/js/semantic.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/plugins/js/mode-markdown.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/plugins/js/ext-language_tools.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/plugins/js/theme-github.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/plugins/js/highlight.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/plugins/js/resizable.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/plugins/js/emojis.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'vendor/martor/js/martor.min.js' %}"></script>
        {% endblock %} <!-- head_base_script -->

        {% endblock %} <!-- block content -->
    </head>
    {% endblock %} <!-- block head -->
    <!-- BODY -->
    {% block page %}
    <body>
        <!-- Navigation -->
        {% block nav %}
        <nav class="navbar-expand-lg navbar-dark bg-dark" style="height:50px">
            <div class='container-fluid'>
                <!-- header -->
                <a href="{% url 'home:index' %}" class="float-left text-center">
                    <img  src="{% static 'home/images/henry_head_portrait.jpg' %}" class='rounded-circle' width="96" height="96">
                    <br>
                    <font face='Satisfy' color="white">Henry Yang</font>
                </a>
                <!-- -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#topNavBar" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class='navbar-toggler-icon'></span>
                </button>
                <!-- ITEMS -->
                <div class='collapse navbar-collapse' id='topNavBar'>
                    <ui class='nav navbar-nav ml-auto'>
                        <!-- BLOG -->
                        <li class='nav-item'>
                            <a class='nav-link' href="{% url 'blog:index' %}">
                                Blog
                            </a>
                        </li>
                        <!-- ABOUT -->
                        <li class='nav-item'>
                            <a class='nav-link' href="{% url 'home:about' %}">
                                About
                            </a>
                        </li>
                        <!-- CONTACT -->
                        <li class='nav-item'>
                            <a class='nav-link' href="{% url 'home:contact' %}">
                                Contact
                            </a>
                        </li>
                    </ui>


                </div>
            </div>
        </nav>
        <!-- endblock nav -->
        {% endblock %}
        <!-- Page Header -->
        {% block page_header %}
        <header class="masthead" style="background-color: rgb(46,94,168); height:80px">
            <div class="overlay"></div>
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 col-md-10 mx-auto">
                        <div class="site-heading">
                          {% block page_header_content %}
                          <h1 class="text-center" style="color: white"> Welcome to Henry's Homepage</h1>
                          {% endblock %}
                        </div>
                    </div>
                </div>
            </div>
        </header>
        {% endblock %}
        <!-- user define body -->
        {% block body %}
        {% endblock %}


    </body>
    <!-- endblock page -->
    {% endblock %}

    <!-- Footer -->
    <footer>
        <div class="container fixed-bottom">
            {% block footer %}
            <p class="copyright text-muted text-right">Copyright &copy; yanghengmonkey@icloud.com 2019</p>
            {% endblock %}
        </div>
    </footer>

</html>